repositories {
	flatDir {
		dirs 'lib-ext'
	}
}

dependencies {
	compile group: "com.dropbox.core", name: "dropbox-core-sdk", version: "1.8.1"
	compile name: "dl-repository-shared-7.0.0.1"
	compile group: "org.osgi", name: "org.osgi.compendium", version: "5.0.0"
	compile group: "org.osgi", name: "org.osgi.core", version: "5.0.0"
	compile project(":apps:document-library:document-library-repository-dropbox-api")
	compile project(":apps:document-library:document-library-repository-dropbox-service")
}

liferay {
	deployDir = file("${liferayHome}/osgi/modules")
}