/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portlet.documentlibrary.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.document.library.kernel.model.DLPreview;
import com.liferay.document.library.kernel.model.DLPreviewModel;
import com.liferay.document.library.kernel.model.DLPreviewSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.petra.string.StringBundler;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the DLPreview service. Represents a row in the &quot;DLPreview&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link DLPreviewModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DLPreviewImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DLPreviewImpl
 * @see DLPreview
 * @see DLPreviewModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class DLPreviewModelImpl extends BaseModelImpl<DLPreview>
	implements DLPreviewModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a document library preview model instance should use the {@link DLPreview} interface instead.
	 */
	public static final String TABLE_NAME = "DLPreview";
	public static final Object[][] TABLE_COLUMNS = {
			{ "filePreviewId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "fileEntryId", Types.BIGINT },
			{ "fileVersionId", Types.BIGINT },
			{ "status", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("filePreviewId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("fileEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("fileVersionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("status", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table DLPreview (filePreviewId LONG not null primary key,groupId LONG,fileEntryId LONG,fileVersionId LONG,status VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table DLPreview";
	public static final String ORDER_BY_JPQL = " ORDER BY dlPreview.filePreviewId DESC";
	public static final String ORDER_BY_SQL = " ORDER BY DLPreview.filePreviewId DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.portal.util.PropsUtil.get(
				"value.object.entity.cache.enabled.com.liferay.document.library.kernel.model.DLPreview"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.portal.util.PropsUtil.get(
				"value.object.finder.cache.enabled.com.liferay.document.library.kernel.model.DLPreview"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.portal.util.PropsUtil.get(
				"value.object.column.bitmask.enabled.com.liferay.document.library.kernel.model.DLPreview"),
			true);
	public static final long FILEENTRYID_COLUMN_BITMASK = 1L;
	public static final long FILEVERSIONID_COLUMN_BITMASK = 2L;
	public static final long FILEPREVIEWID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static DLPreview toModel(DLPreviewSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		DLPreview model = new DLPreviewImpl();

		model.setFilePreviewId(soapModel.getFilePreviewId());
		model.setGroupId(soapModel.getGroupId());
		model.setFileEntryId(soapModel.getFileEntryId());
		model.setFileVersionId(soapModel.getFileVersionId());
		model.setStatus(soapModel.getStatus());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<DLPreview> toModels(DLPreviewSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<DLPreview> models = new ArrayList<DLPreview>(soapModels.length);

		for (DLPreviewSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.portal.util.PropsUtil.get(
				"lock.expiration.time.com.liferay.document.library.kernel.model.DLPreview"));

	public DLPreviewModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _filePreviewId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFilePreviewId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _filePreviewId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DLPreview.class;
	}

	@Override
	public String getModelClassName() {
		return DLPreview.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("filePreviewId", getFilePreviewId());
		attributes.put("groupId", getGroupId());
		attributes.put("fileEntryId", getFileEntryId());
		attributes.put("fileVersionId", getFileVersionId());
		attributes.put("status", getStatus());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long filePreviewId = (Long)attributes.get("filePreviewId");

		if (filePreviewId != null) {
			setFilePreviewId(filePreviewId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long fileEntryId = (Long)attributes.get("fileEntryId");

		if (fileEntryId != null) {
			setFileEntryId(fileEntryId);
		}

		Long fileVersionId = (Long)attributes.get("fileVersionId");

		if (fileVersionId != null) {
			setFileVersionId(fileVersionId);
		}

		String status = (String)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}
	}

	@JSON
	@Override
	public long getFilePreviewId() {
		return _filePreviewId;
	}

	@Override
	public void setFilePreviewId(long filePreviewId) {
		_columnBitmask = -1L;

		_filePreviewId = filePreviewId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getFileEntryId() {
		return _fileEntryId;
	}

	@Override
	public void setFileEntryId(long fileEntryId) {
		_columnBitmask |= FILEENTRYID_COLUMN_BITMASK;

		if (!_setOriginalFileEntryId) {
			_setOriginalFileEntryId = true;

			_originalFileEntryId = _fileEntryId;
		}

		_fileEntryId = fileEntryId;
	}

	public long getOriginalFileEntryId() {
		return _originalFileEntryId;
	}

	@JSON
	@Override
	public long getFileVersionId() {
		return _fileVersionId;
	}

	@Override
	public void setFileVersionId(long fileVersionId) {
		_columnBitmask |= FILEVERSIONID_COLUMN_BITMASK;

		if (!_setOriginalFileVersionId) {
			_setOriginalFileVersionId = true;

			_originalFileVersionId = _fileVersionId;
		}

		_fileVersionId = fileVersionId;
	}

	public long getOriginalFileVersionId() {
		return _originalFileVersionId;
	}

	@JSON
	@Override
	public String getStatus() {
		if (_status == null) {
			return "";
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		_status = status;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			DLPreview.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DLPreview toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (DLPreview)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DLPreviewImpl dlPreviewImpl = new DLPreviewImpl();

		dlPreviewImpl.setFilePreviewId(getFilePreviewId());
		dlPreviewImpl.setGroupId(getGroupId());
		dlPreviewImpl.setFileEntryId(getFileEntryId());
		dlPreviewImpl.setFileVersionId(getFileVersionId());
		dlPreviewImpl.setStatus(getStatus());

		dlPreviewImpl.resetOriginalValues();

		return dlPreviewImpl;
	}

	@Override
	public int compareTo(DLPreview dlPreview) {
		int value = 0;

		if (getFilePreviewId() < dlPreview.getFilePreviewId()) {
			value = -1;
		}
		else if (getFilePreviewId() > dlPreview.getFilePreviewId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof DLPreview)) {
			return false;
		}

		DLPreview dlPreview = (DLPreview)obj;

		long primaryKey = dlPreview.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		DLPreviewModelImpl dlPreviewModelImpl = this;

		dlPreviewModelImpl._originalFileEntryId = dlPreviewModelImpl._fileEntryId;

		dlPreviewModelImpl._setOriginalFileEntryId = false;

		dlPreviewModelImpl._originalFileVersionId = dlPreviewModelImpl._fileVersionId;

		dlPreviewModelImpl._setOriginalFileVersionId = false;

		dlPreviewModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<DLPreview> toCacheModel() {
		DLPreviewCacheModel dlPreviewCacheModel = new DLPreviewCacheModel();

		dlPreviewCacheModel.filePreviewId = getFilePreviewId();

		dlPreviewCacheModel.groupId = getGroupId();

		dlPreviewCacheModel.fileEntryId = getFileEntryId();

		dlPreviewCacheModel.fileVersionId = getFileVersionId();

		dlPreviewCacheModel.status = getStatus();

		String status = dlPreviewCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			dlPreviewCacheModel.status = null;
		}

		return dlPreviewCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{filePreviewId=");
		sb.append(getFilePreviewId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", fileEntryId=");
		sb.append(getFileEntryId());
		sb.append(", fileVersionId=");
		sb.append(getFileVersionId());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append("com.liferay.document.library.kernel.model.DLPreview");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>filePreviewId</column-name><column-value><![CDATA[");
		sb.append(getFilePreviewId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fileEntryId</column-name><column-value><![CDATA[");
		sb.append(getFileEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fileVersionId</column-name><column-value><![CDATA[");
		sb.append(getFileVersionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = DLPreview.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			DLPreview.class, ModelWrapper.class
		};
	private long _filePreviewId;
	private long _groupId;
	private long _fileEntryId;
	private long _originalFileEntryId;
	private boolean _setOriginalFileEntryId;
	private long _fileVersionId;
	private long _originalFileVersionId;
	private boolean _setOriginalFileVersionId;
	private String _status;
	private long _columnBitmask;
	private DLPreview _escapedModel;
}