/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portlet.documentlibrary.service.base;

import com.liferay.document.library.kernel.model.DLPreview;
import com.liferay.document.library.kernel.service.DLPreviewService;
import com.liferay.document.library.kernel.service.persistence.DLPreviewPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the document library preview remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.portlet.documentlibrary.service.impl.DLPreviewServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.portlet.documentlibrary.service.impl.DLPreviewServiceImpl
 * @see com.liferay.document.library.kernel.service.DLPreviewServiceUtil
 * @generated
 */
public abstract class DLPreviewServiceBaseImpl extends BaseServiceImpl
	implements DLPreviewService, IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.liferay.document.library.kernel.service.DLPreviewServiceUtil} to access the document library preview remote service.
	 */

	/**
	 * Returns the document library preview local service.
	 *
	 * @return the document library preview local service
	 */
	public com.liferay.document.library.kernel.service.DLPreviewLocalService getDLPreviewLocalService() {
		return dlPreviewLocalService;
	}

	/**
	 * Sets the document library preview local service.
	 *
	 * @param dlPreviewLocalService the document library preview local service
	 */
	public void setDLPreviewLocalService(
		com.liferay.document.library.kernel.service.DLPreviewLocalService dlPreviewLocalService) {
		this.dlPreviewLocalService = dlPreviewLocalService;
	}

	/**
	 * Returns the document library preview remote service.
	 *
	 * @return the document library preview remote service
	 */
	public DLPreviewService getDLPreviewService() {
		return dlPreviewService;
	}

	/**
	 * Sets the document library preview remote service.
	 *
	 * @param dlPreviewService the document library preview remote service
	 */
	public void setDLPreviewService(DLPreviewService dlPreviewService) {
		this.dlPreviewService = dlPreviewService;
	}

	/**
	 * Returns the document library preview persistence.
	 *
	 * @return the document library preview persistence
	 */
	public DLPreviewPersistence getDLPreviewPersistence() {
		return dlPreviewPersistence;
	}

	/**
	 * Sets the document library preview persistence.
	 *
	 * @param dlPreviewPersistence the document library preview persistence
	 */
	public void setDLPreviewPersistence(
		DLPreviewPersistence dlPreviewPersistence) {
		this.dlPreviewPersistence = dlPreviewPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return DLPreviewService.class.getName();
	}

	protected Class<?> getModelClass() {
		return DLPreview.class;
	}

	protected String getModelClassName() {
		return DLPreview.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = dlPreviewPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.liferay.document.library.kernel.service.DLPreviewLocalService.class)
	protected com.liferay.document.library.kernel.service.DLPreviewLocalService dlPreviewLocalService;
	@BeanReference(type = DLPreviewService.class)
	protected DLPreviewService dlPreviewService;
	@BeanReference(type = DLPreviewPersistence.class)
	protected DLPreviewPersistence dlPreviewPersistence;
	@BeanReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
}