/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portlet.documentlibrary.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.document.library.kernel.model.DLPreview;
import com.liferay.document.library.kernel.service.DLPreviewLocalService;
import com.liferay.document.library.kernel.service.persistence.DLPreviewPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the document library preview local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.portlet.documentlibrary.service.impl.DLPreviewLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.portlet.documentlibrary.service.impl.DLPreviewLocalServiceImpl
 * @see com.liferay.document.library.kernel.service.DLPreviewLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class DLPreviewLocalServiceBaseImpl extends BaseLocalServiceImpl
	implements DLPreviewLocalService, IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.liferay.document.library.kernel.service.DLPreviewLocalServiceUtil} to access the document library preview local service.
	 */

	/**
	 * Adds the document library preview to the database. Also notifies the appropriate model listeners.
	 *
	 * @param dlPreview the document library preview
	 * @return the document library preview that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public DLPreview addDLPreview(DLPreview dlPreview) {
		dlPreview.setNew(true);

		return dlPreviewPersistence.update(dlPreview);
	}

	/**
	 * Creates a new document library preview with the primary key. Does not add the document library preview to the database.
	 *
	 * @param filePreviewId the primary key for the new document library preview
	 * @return the new document library preview
	 */
	@Override
	@Transactional(enabled = false)
	public DLPreview createDLPreview(long filePreviewId) {
		return dlPreviewPersistence.create(filePreviewId);
	}

	/**
	 * Deletes the document library preview with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param filePreviewId the primary key of the document library preview
	 * @return the document library preview that was removed
	 * @throws PortalException if a document library preview with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public DLPreview deleteDLPreview(long filePreviewId)
		throws PortalException {
		return dlPreviewPersistence.remove(filePreviewId);
	}

	/**
	 * Deletes the document library preview from the database. Also notifies the appropriate model listeners.
	 *
	 * @param dlPreview the document library preview
	 * @return the document library preview that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public DLPreview deleteDLPreview(DLPreview dlPreview) {
		return dlPreviewPersistence.remove(dlPreview);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(DLPreview.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return dlPreviewPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.portlet.documentlibrary.model.impl.DLPreviewModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return dlPreviewPersistence.findWithDynamicQuery(dynamicQuery, start,
			end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.portlet.documentlibrary.model.impl.DLPreviewModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return dlPreviewPersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return dlPreviewPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return dlPreviewPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public DLPreview fetchDLPreview(long filePreviewId) {
		return dlPreviewPersistence.fetchByPrimaryKey(filePreviewId);
	}

	/**
	 * Returns the document library preview with the primary key.
	 *
	 * @param filePreviewId the primary key of the document library preview
	 * @return the document library preview
	 * @throws PortalException if a document library preview with the primary key could not be found
	 */
	@Override
	public DLPreview getDLPreview(long filePreviewId) throws PortalException {
		return dlPreviewPersistence.findByPrimaryKey(filePreviewId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(dlPreviewLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(DLPreview.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("filePreviewId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(dlPreviewLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(DLPreview.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"filePreviewId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(dlPreviewLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(DLPreview.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("filePreviewId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return dlPreviewLocalService.deleteDLPreview((DLPreview)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return dlPreviewPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the document library previews.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.portlet.documentlibrary.model.impl.DLPreviewModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of document library previews
	 * @param end the upper bound of the range of document library previews (not inclusive)
	 * @return the range of document library previews
	 */
	@Override
	public List<DLPreview> getDLPreviews(int start, int end) {
		return dlPreviewPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of document library previews.
	 *
	 * @return the number of document library previews
	 */
	@Override
	public int getDLPreviewsCount() {
		return dlPreviewPersistence.countAll();
	}

	/**
	 * Updates the document library preview in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param dlPreview the document library preview
	 * @return the document library preview that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public DLPreview updateDLPreview(DLPreview dlPreview) {
		return dlPreviewPersistence.update(dlPreview);
	}

	/**
	 * Returns the document library preview local service.
	 *
	 * @return the document library preview local service
	 */
	public DLPreviewLocalService getDLPreviewLocalService() {
		return dlPreviewLocalService;
	}

	/**
	 * Sets the document library preview local service.
	 *
	 * @param dlPreviewLocalService the document library preview local service
	 */
	public void setDLPreviewLocalService(
		DLPreviewLocalService dlPreviewLocalService) {
		this.dlPreviewLocalService = dlPreviewLocalService;
	}

	/**
	 * Returns the document library preview persistence.
	 *
	 * @return the document library preview persistence
	 */
	public DLPreviewPersistence getDLPreviewPersistence() {
		return dlPreviewPersistence;
	}

	/**
	 * Sets the document library preview persistence.
	 *
	 * @param dlPreviewPersistence the document library preview persistence
	 */
	public void setDLPreviewPersistence(
		DLPreviewPersistence dlPreviewPersistence) {
		this.dlPreviewPersistence = dlPreviewPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("com.liferay.document.library.kernel.model.DLPreview",
			dlPreviewLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.liferay.document.library.kernel.model.DLPreview");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return DLPreviewLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return DLPreview.class;
	}

	protected String getModelClassName() {
		return DLPreview.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = dlPreviewPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = DLPreviewLocalService.class)
	protected DLPreviewLocalService dlPreviewLocalService;
	@BeanReference(type = DLPreviewPersistence.class)
	protected DLPreviewPersistence dlPreviewPersistence;
	@BeanReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@BeanReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}