dependencies {
	compileInclude group: "commons-httpclient", name: "commons-httpclient", version: "3.1"
	compileInclude group: "net.sourceforge.nekohtml", name: "nekohtml", version: "1.9.16"
	compileInclude group: "org.apache.xmlgraphics", name: "batik-css", version: "1.7"
	compileInclude group: "org.apache.xmlgraphics", name: "batik-ext", version: "1.7"
	compileInclude group: "org.apache.xmlgraphics", name: "batik-util", version: "1.7"
	compileInclude group: "org.owasp.antisamy", name: "antisamy", version: "1.5.3"
	compileInclude group: "xml-apis", name: "xml-apis-ext", version: "1.3.04"

	provided group: "biz.aQute.bnd", name: "biz.aQute.bndlib", version: "3.1.0"
	provided group: "com.liferay", name: "com.liferay.portal.configuration.metatype", version: "2.0.0"
	provided group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "2.49.0"
	provided group: "org.osgi", name: "org.osgi.core", version: "5.0.0"
	provided group: "org.osgi", name: "org.osgi.service.component.annotations", version: "1.3.0"
	provided group: "xerces", name: "xercesImpl", version: "2.9.1"
	provided group: "xml-apis", name: "xml-apis", version: "1.3.04"
	provided project(":apps:foundation:portal-security:portal-security-antisamy:portal-security-antisamy-api")
}