/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.liferaygen.web.internal.actions.journal;

import com.liferay.liferaygen.config.ConfigUtil;
import com.liferay.liferaygen.constants.ConfigConstants;
import com.liferay.liferaygen.impl.BaseAction;
import com.liferay.liferaygen.util.ParameterUtil;
import com.liferay.liferaygen.util.ValueGenerator;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.template.TemplateConstants;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.MapUtil;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.kernel.xml.Document;
import com.liferay.portal.kernel.xml.Element;
import com.liferay.portal.kernel.xml.SAXReaderUtil;
import com.liferay.portal.service.ClassNameLocalServiceUtil;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portlet.dynamicdatamapping.model.DDMStructure;
import com.liferay.portlet.dynamicdatamapping.model.DDMStructureConstants;
import com.liferay.portlet.dynamicdatamapping.model.DDMTemplateConstants;
import com.liferay.portlet.dynamicdatamapping.service.DDMStructureLocalServiceUtil;
import com.liferay.portlet.dynamicdatamapping.service.DDMTemplateLocalServiceUtil;
import com.liferay.portlet.journal.model.JournalArticle;

import java.io.IOException;
import java.io.InputStream;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.TreeMap;

import static com.liferay.liferaygen.util.ValueGenerator.getRandomIntegerFromRange;
public class CreateJournalStructure extends BaseAction {

	@Override
	public String doGetDescription() {
		return "Creates a random webcontent structure";
	}

	@Override
	@SuppressWarnings("serial")
	public Map<String, Object> doGetParametersDefaultValues() {
		return new TreeMap<String, Object>() {
			{
				put("addTemplate", Boolean.TRUE);
				put("childRatio", DEFAULT_CHILD_RATIO);
				put("localizedFieldRatio", DEFAULT_LOCALIZED_FIELD_RATIO);
				put("maxWcmImages", DEFAULT_MAX_WCM_IMAGES);
				put("repeatableFieldRatio", DEFAULT_REPEATABLE_FIELD_RATIO);
			}
		};
	}

	@Override
	@SuppressWarnings("serial")
	public Map<String, String> doGetParametersDescription() {
		return new TreeMap<String, String>() {
			{
				put(
					"addTemplate",
					"Add a autogenerated template after creating the " +
					"structure");
				put(
					"childRatio",
					"Probability percentage of creating a child structure " +
					"with a random parent");
				put(
					"localizedFieldRatio",
					"Percentage of localized fields per structure");
				put("maxWcmImages", "Max number of WCM Images per structure");
				put(
					"repeatableFieldRatio",
					"Percentage of repeatable fields per structure");
			}
		};
	}

	protected static String getVMTemplateContent() throws IOException {
		ClassLoader classLoader = ConfigUtil.class.getClassLoader();

		InputStream inputStream = classLoader.getResourceAsStream(
			"com/liferay/liferaygen/resources/WCTemplate.vm");

		String template = StringUtil.read(inputStream);

		template += "\n\n";

		return template;
	}

	protected void addTemplate(DDMStructure journalStructure) throws Exception {
		String xsl = getVMTemplateContent();

		Element rootElement = getStructureElements(journalStructure);

		List<Element> dynamicElements = rootElement.elements("dynamic-element");

		for (Element dynamicElement : dynamicElements) {
			String elementName = dynamicElement.attributeValue("name");

			xsl = xsl + "#runfield($" + elementName + ")\n";
		}

		long userId = ValueGenerator.getRandomUserIdFromCache();

		Locale[] locales = (Locale[]) _parameters.get(ConfigConstants.LOCALES);

		Map<Locale, String> nameMap =
			ValueGenerator.getRandomValuesLocalizationMap(locales, NAME_LENGTH);

		Map<Locale, String> descriptionMap =
			ValueGenerator.getRandomValuesLocalizationMap(
				locales, DESCRIPTION_LENGTH);

		long structureClassnameId = ClassNameLocalServiceUtil.getClassNameId(
			DDMStructure.class);

		DDMTemplateLocalServiceUtil.addTemplate(
			userId, journalStructure.getGroupId(), structureClassnameId,
			journalStructure.getStructureId(), nameMap, descriptionMap,
			DDMTemplateConstants.TEMPLATE_TYPE_DISPLAY, StringPool.BLANK,
			TemplateConstants.LANG_TYPE_VM, xsl, new ServiceContext());
	}

	protected void appendParentStructureElements(
			long groupId, long parentStructureId, Element rootElement)
		throws Exception {

		if (Validator.isNull(parentStructureId)) {
			return;
		}

		//Todo - implement the case with global group when needed
		DDMStructure parentStructure =
			DDMStructureLocalServiceUtil.getDDMStructure(parentStructureId);

		appendParentStructureElements(
			groupId, parentStructure.getParentStructureId(), rootElement);

		Document document = SAXReaderUtil.read(parentStructure.getXsd());

		if (rootElement == null) {
			rootElement = document.getRootElement();
		}
		else {
			rootElement.add(document.getRootElement());
		}
	}

	protected void doRun() {
		try {
			long groupId = GetterUtil.getLong(
				_parameters.get(ConfigConstants.GROUP_ID));

			long userId = ValueGenerator.getRandomUserIdFromCache();

			long parentStructureId = 0L;

			int childRatio =
				ParameterUtil.getParamAsIntegerPercentage(
					_parameters, "childRatio");

			boolean isChild = ValueGenerator.getBoolean(childRatio);

			if (isChild) {
				DDMStructure parentStructure = getRandomStructure(groupId);

				if ((parentStructure != null) &&
					Validator.isNull(
							parentStructure.getParentStructureId())) {

					parentStructureId = parentStructure.getStructureId();
				}
			}

			Locale[] locales = (Locale[]) _parameters.get(
				ConfigConstants.LOCALES);

			Map<Locale, String> nameMap =
				ValueGenerator.getRandomValuesLocalizationMap(
					locales, NAME_LENGTH);

			Map<Locale, String> descriptionMap =
				ValueGenerator.getRandomValuesLocalizationMap(
					locales, DESCRIPTION_LENGTH);

			Document document = SAXReaderUtil.createDocument();

			Element rootElement = document.addElement("root");

			rootElement.addAttribute(
				"available-locales", LocaleUtil.getSiteDefault().toString());
			rootElement.addAttribute(
				"default-locale", LocaleUtil.getSiteDefault().toString());

			_maxWcmImages = GetterUtil.getInteger(
				_parameters.get("maxWcmImages"));

			boolean allowWcmImages = true;

			if (_maxWcmImages == 0) {
				allowWcmImages = false;
			}

			generateRandomStructureContent(rootElement, 1, allowWcmImages);

			ServiceContext serviceContext = new ServiceContext();

			long journalClassnameId = ClassNameLocalServiceUtil.getClassNameId(
				JournalArticle.class);

			DDMStructure journalStructure =
				DDMStructureLocalServiceUtil.addStructure(
					userId, groupId, parentStructureId, journalClassnameId,
					null, nameMap, descriptionMap, document.formattedString(),
					"xml", DDMStructureConstants.TYPE_DEFAULT, serviceContext);

			boolean addTemplate = Boolean.parseBoolean(
				MapUtil.getString(_parameters, "addTemplate"));

			if (!addTemplate) {
				return;
			}

			addTemplate(journalStructure);
		}
		catch (Exception e) {
			_log.error(e, e);
		}
	}

	protected Element generateListOption() {
		Element optionElement = SAXReaderUtil.createElement("dynamic-element");

		String name = ValueGenerator.getLowerCaseText(
			getRandomIntegerFromRange(5, 12));

		name = name.replace(" ", "");

		optionElement.addAttribute("name", name);

		optionElement.addAttribute("type", "option");

		optionElement.addAttribute("value", name + "_value");

		Element metadataElement = SAXReaderUtil.createElement("meta-data");

		metadataElement.addAttribute(
			"locale", LocaleUtil.getSiteDefault().toString());

		Element entryElement = SAXReaderUtil.createElement("entry");

		entryElement.addAttribute("name", "label");

		entryElement.addCDATA(name + "_label");

		metadataElement.add(entryElement);

		optionElement.add(metadataElement);

		return optionElement;
	}

	protected Element generateListOptions(Element element) {
		int numOptions = getRandomIntegerFromRange(2, 10);

		for (int i = 0; i < numOptions; i++) {
			Element optionElement = generateListOption();

			element.add(optionElement);
		}

		return element;
	}

	protected void generateRandomStructureContent(
		Element rootElement, int depth, boolean allowWcmImages) {

		int maxFields = MAX_FIELDS_PER_LEVEL;

		if (depth > 1) {
			maxFields = MAX_FIELDS_PER_CHILD_LEVEL;
		}

		int numFields = getRandomIntegerFromRange(1, maxFields);

		int numWcmImages = 0;

		for (int i = 0; i < numFields; i++) {
			Element element = generateRandomStructureElement(allowWcmImages);

			rootElement.add(element);

			String type = element.attributeValue("type");

			if (type.equals("wcm-image")) {
				if (numWcmImages == _maxWcmImages) {
					allowWcmImages = false;
				}
				else {
					numWcmImages++;
				}
			}

			//List fields don't allow child fields

			if (!type.equals("radio") && !type.equals("select")) {
				boolean hasChildren = ValueGenerator.getBoolean();

				if (hasChildren && (depth <= MAX_DEPTH)) {
					generateRandomStructureContent(
						element, depth + 1, allowWcmImages);
				}
			}

			String nameValue = element.attributeValue("name");

			Element metadataElement = SAXReaderUtil.createElement("meta-data");

			metadataElement.addAttribute(
				"locale", LocaleUtil.getSiteDefault().toString());

			Element entryLabelElement = SAXReaderUtil.createElement("entry");

			entryLabelElement.addAttribute("name", "label");

			entryLabelElement.addCDATA(nameValue + "_label");

			metadataElement.add(entryLabelElement);

			Element entryPredefinedValueElement = SAXReaderUtil.createElement(
				"entry");

			entryPredefinedValueElement.addAttribute("name", "predefinedValue");

			// TODO Generate proper predefined values

			entryPredefinedValueElement.addCDATA("");

			metadataElement.add(entryPredefinedValueElement);

			Element entryTipElement = SAXReaderUtil.createElement("entry");

			entryTipElement.addAttribute("name", "tip");

			entryTipElement.addCDATA(nameValue + "_tip");

			metadataElement.add(entryTipElement);

			element.add(metadataElement);
		}
	}

	protected Element generateRandomStructureElement(boolean allowWcmImages) {
		Element element = SAXReaderUtil.createElement("dynamic-element");

		String typeValue;

		if (!allowWcmImages) {
			typeValue = ValueGenerator.getRandomObjectFromList(
				JOURNALSTRUCTURE_FIELD_TYPES_NO_WCM_IMAGE);
		}
		else {
			typeValue = ValueGenerator.getRandomObjectFromList(
				JOURNALSTRUCTURE_FIELD_TYPES);
		}

		element.addAttribute("type", typeValue);

		if (!typeValue.equals("ddm-separator")) {
			String dataTypeValue = JOURNALSTRUCTURE_FIELD_DATATYPES.get(
				JOURNALSTRUCTURE_FIELD_TYPES.indexOf(typeValue));

			element.addAttribute("dataType", dataTypeValue);
		}

		String fieldNamespaceValue = typeValue.substring(0, 4);

		if (fieldNamespaceValue.endsWith("-")) {
			element.addAttribute(
				"fieldNamespace", fieldNamespaceValue.substring(0, 3));
		}

		int nameLength = getRandomIntegerFromRange(5, 12);

		String nameValue = ValueGenerator.getLowerCaseWord(nameLength);

		element.addAttribute("name", nameValue);

		int repeatableFieldRatio =
			ParameterUtil.getParamAsIntegerPercentage(
				_parameters, "repeatableFieldRatio");

		String repeatableValue = String.valueOf(
			ValueGenerator.getBoolean(repeatableFieldRatio));

		element.addAttribute("repeatable", repeatableValue);

		String readOnlyValue = String.valueOf(ValueGenerator.getBoolean());

		element.addAttribute("readOnly", readOnlyValue);

		String showLabelValue = String.valueOf(ValueGenerator.getBoolean());

		element.addAttribute("showLabel", showLabelValue);

		int localizedFieldRatio =
			ParameterUtil.getParamAsIntegerPercentage(
				_parameters, "localizedFieldRatio");

		String localizableValue = String.valueOf(
			ValueGenerator.getBoolean(localizedFieldRatio));

		element.addAttribute("localizable", localizableValue);

		if (typeValue.equals("checkbox") ||
			typeValue.equals("ddm-documentlibrary") ||
			typeValue.equals("wcm-image") || typeValue.equals("radio") ||
			typeValue.equals("select") ||
			typeValue.equals("ddm-separator")) {

			element.addAttribute("width", "");
		}
		else {
			String widthValue = String.valueOf(
				ValueGenerator.getRandomObjectFromArray(WIDTHS));

			element.addAttribute("width", widthValue);
		}

		String indexTypeValue;

		if (typeValue.contains("text")) {
			indexTypeValue = ValueGenerator.getRandomObjectFromList(
				INDEX_TYPE_FIELD_TYPES_WITH_TEXT);
		}
		else {
			indexTypeValue = ValueGenerator.getRandomObjectFromList(
				INDEX_TYPE_FIELD_TYPES);
		}

		element.addAttribute("indexType", indexTypeValue);

		if (typeValue.equals("radio") || typeValue.equals("select")) {
			element = generateListOptions(element);

			if (typeValue.equals("select")) {
				String multipleValue = String.valueOf(
					ValueGenerator.getBoolean());

				element.addAttribute("multiple", multipleValue);
			}
		}

		return element;
	}

	protected DDMStructure getRandomStructure(long groupId)
		throws SystemException {

		int count = DDMStructureLocalServiceUtil.getStructuresCount(groupId);

		if (count == 0) {
			return null;
		}

		int randomPos = getRandomIntegerFromRange(0, count -1);

		List<DDMStructure> journalStructures =
			DDMStructureLocalServiceUtil.getStructures(
				groupId, randomPos, randomPos + 1);

		return journalStructures.get(0);
	}

	protected Element getStructureElements(DDMStructure journalStructure)
		throws Exception {

		Element rootElement = null;

		appendParentStructureElements(
			journalStructure.getGroupId(),
			journalStructure.getParentStructureId(), rootElement);

		Document document = SAXReaderUtil.read(
			journalStructure.getCompleteXsd());

		if (rootElement == null) {
			rootElement = document.getRootElement();
		}
		else {
			rootElement.add(document.getRootElement());
		}

		return rootElement;
	}

	private static final int DEFAULT_CHILD_RATIO = 25;

	private static final int DEFAULT_LOCALIZED_FIELD_RATIO = 60;

	private static final int DEFAULT_MAX_WCM_IMAGES = 1;

	private static final int DEFAULT_REPEATABLE_FIELD_RATIO = 20;

	private static final int DESCRIPTION_LENGTH = 20;

	private static final List<String> INDEX_TYPE_FIELD_TYPES =
			new ArrayList<String>(Arrays.asList("keyword", StringPool.BLANK));

	private static final List<String> INDEX_TYPE_FIELD_TYPES_WITH_TEXT =
		new ArrayList<String>(
			Arrays.asList("text", "keyword", StringPool.BLANK));

	private static final List<String> JOURNALSTRUCTURE_FIELD_DATATYPES =
		new ArrayList<String>(Arrays.asList(
			"boolean", "date", "double", "document-library", "html", "image",
			"integer", "link-to-page", "number", "string", "string",
			StringPool.BLANK, "string", "string"));

	private static final List<String> JOURNALSTRUCTURE_FIELD_TYPES =
		new ArrayList<String>(Arrays.asList(
			"checkbox", "ddm-date", "ddm-decimal", "ddm-documentlibrary",
			"ddm-text-html", "wcm-image", "ddm-integer", "ddm-link-to-page",
			"ddm-number", "radio", "select", "ddm-separator", "text",
			"textarea"));

	private static final List<String>
		JOURNALSTRUCTURE_FIELD_TYPES_NO_WCM_IMAGE =
			new ArrayList<String>(Arrays.asList(
				"checkbox", "ddm-date", "ddm-decimal", "ddm-documentlibrary",
				"ddm-text-html", "ddm-integer", "ddm-link-to-page",
				"ddm-number", "radio", "select", "ddm-separator", "text",
				"textarea"));

	private static final int MAX_DEPTH = 3;

	private static final int MAX_FIELDS_PER_CHILD_LEVEL = 3;

	private static final int MAX_FIELDS_PER_LEVEL = 8;

	private static final int NAME_LENGTH = 10;

	private static final String[] WIDTHS = {"small", "medium", "large"};

	private static Log _log = LogFactoryUtil.getLog(
		CreateJournalStructure.class);

	private int _maxWcmImages;

}