/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.liferaygen.journal.internal;

import com.liferay.dynamic.data.mapping.model.DDMStructure;
import com.liferay.dynamic.data.mapping.model.DDMStructureConstants;
import com.liferay.dynamic.data.mapping.model.DDMTemplateConstants;
import com.liferay.dynamic.data.mapping.service.DDMStructureLocalService;
import com.liferay.dynamic.data.mapping.service.DDMTemplateLocalService;
import com.liferay.expando.kernel.service.ExpandoValueLocalService;
import com.liferay.journal.model.JournalArticle;
import com.liferay.journal.service.JournalArticleLocalService;
import com.liferay.liferaygen.BaseLiferayGenAction;
import com.liferay.liferaygen.LiferayGenAction;
import com.liferay.liferaygen.constants.LiferayGenConfigConstants;
import com.liferay.liferaygen.util.LiferayGenParameterHandler;
import com.liferay.liferaygen.util.LiferayGenQueryHandler;
import com.liferay.liferaygen.value.generator.LiferayGenValueGenerator;
import com.liferay.petra.string.StringBundler;
import com.liferay.petra.string.StringPool;
import com.liferay.portal.kernel.service.ClassNameLocalService;
import com.liferay.portal.kernel.service.CompanyLocalService;
import com.liferay.portal.kernel.service.PortletLocalService;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.template.TemplateConstants;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.MapUtil;
import com.liferay.portal.kernel.util.Portal;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.xml.Document;
import com.liferay.portal.kernel.xml.Element;
import com.liferay.portal.kernel.xml.SAXReaderUtil;

import java.io.IOException;
import java.io.InputStream;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.TreeMap;

import org.osgi.service.component.annotations.Component;
import org.osgi.service.component.annotations.Reference;

/**
 * @author Jorge Díaz
 * @author Alberto Chaparro
 * @author Daniel Couso
 * @author Roberto Díaz
 */
@Component(
	immediate = true,
	properties = "liferaygen.action.class.name=com.liferay.liferaygen.journal.internal.CreateJournalStructureLiferayGenAction",
	service = LiferayGenAction.class
)
public class CreateJournalStructureLiferayGenAction
	extends BaseLiferayGenAction {

	@Override
	public String doGetDescription() {
		return "Creates a random webcontent structure";
	}

	@Override
	@SuppressWarnings("serial")
	public Map<String, Object> doGetParametersDefaultValues() {
		return new TreeMap<String, Object>() {
			{
				put("addTemplate", Boolean.TRUE);
				put("childRatio", _DEFAULT_CHILD_RATIO);
				put("localizedFieldRatio", _DEFAULT_LOCALIZED_FIELD_RATIO);
				put("maxWcmImages", _DEFAULT_MAX_WCM_IMAGES);
				put("repeatableFieldRatio", _DEFAULT_REPEATABLE_FIELD_RATIO);
			}
		};
	}

	@Override
	@SuppressWarnings("serial")
	public Map<String, String> doGetParametersDescription() {
		return new TreeMap<String, String>() {
			{
				put(
					"addTemplate",
					"Add a autogenerated template after creating the " +
						"structure");
				put(
					"childRatio",
					"Probability percentage of creating a child structure " +
						"with a random parent");
				put(
					"localizedFieldRatio",
					"Percentage of localized fields per structure");
				put("maxWcmImages", "Max number of WCM Images per structure");
				put(
					"repeatableFieldRatio",
					"Percentage of repeatable fields per structure");
			}
		};
	}

	@Override
	public String getName() {
		return "CreateJournalStructureLiferayGenAction";
	}

	protected static String getVMTemplateContent() throws IOException {
		ClassLoader classLoader =
			CreateJournalStructureLiferayGenAction.class.getClassLoader();

		InputStream inputStream = classLoader.getResourceAsStream(
			"com/liferay/liferaygen/journal/internal/template/WCTemplate.vm");

		String template = StringUtil.read(inputStream);

		template += "\n\n";

		return template;
	}

	protected void addTemplate(
			LiferayGenValueGenerator liferayGenValueGenerator,
			Map<String, Object> parameters, DDMStructure ddmStructure)
		throws Exception {

		String xsl = getVMTemplateContent();

		Element rootElement = getStructureElements(ddmStructure);

		List<Element> dynamicElements = rootElement.elements("dynamic-element");

		for (Element dynamicElement : dynamicElements) {
			String elementName = dynamicElement.attributeValue("name");

			xsl = StringBundler.concat(xsl, "#runfield($", elementName, ")\n");
		}

		long userId = liferayGenValueGenerator.getRandomUserIdFromCache();

		Locale[] locales = (Locale[])parameters.get(
			LiferayGenConfigConstants.LOCALES);

		Map<Locale, String> nameMap =
			liferayGenValueGenerator.getRandomValuesLocalizationMap(
				locales, _NAME_LENGTH);

		Map<Locale, String> descriptionMap =
			liferayGenValueGenerator.getRandomValuesLocalizationMap(
				locales, _DESCRIPTION_LENGTH);

		long structureClassnameId = _classNameLocalService.getClassNameId(
			DDMStructure.class);

		//TODO does it work??
		_ddmTemplateLocalService.addTemplate(
			userId, ddmStructure.getGroupId(), structureClassnameId,
			ddmStructure.getPrimaryKey(), ddmStructure.getStructureId(),
			nameMap, descriptionMap, DDMTemplateConstants.TEMPLATE_TYPE_DISPLAY,
			StringPool.BLANK, TemplateConstants.LANG_TYPE_VM, xsl,
			new ServiceContext());
	}

	protected void appendParentStructureElements(
			long parentStructureId, Element rootElement)
		throws Exception {

		if (parentStructureId == 0) {
			return;
		}

		//Todo - implement the case with global group when needed
		DDMStructure parentStructure =
			_ddmStructureLocalService.getDDMStructure(parentStructureId);

		appendParentStructureElements(
			parentStructure.getParentStructureId(), rootElement);

		//TODO set as null by now
		//Document document = SAXReaderUtil.read(parentStructure.getXsd());
		Document document = null;

		if (rootElement == null) {
			rootElement = document.getRootElement();
		}
		else {
			rootElement.add(document.getRootElement());
		}
	}

	protected void doRun() throws Exception {
		Map<String, Object> parameters = getParameters();

		long groupId = GetterUtil.getLong(
			parameters.get(LiferayGenConfigConstants.GROUP_ID));

		LiferayGenValueGenerator liferayGenValueGenerator =
			new LiferayGenValueGenerator(
				_companyLocalService, _liferayGenQueryHandler, _portal,
				_portletLocalService);

		long userId = liferayGenValueGenerator.getRandomUserIdFromCache();

		long parentStructureId = 0L;

		int childRatio =
			_liferayGenParameterHandler.getParamAsIntegerPercentage(
				parameters, "childRatio");

		boolean child = liferayGenValueGenerator.getBoolean(childRatio);

		if (child) {
			DDMStructure parentStructure = getRandomStructure(
				liferayGenValueGenerator, groupId);

			if ((parentStructure != null) &&
				(parentStructure.getParentStructureId() == 0)) {

				parentStructureId = parentStructure.getStructureId();
			}
		}

		Locale[] locales = (Locale[])parameters.get(
			LiferayGenConfigConstants.LOCALES);

		Map<Locale, String> nameMap =
			liferayGenValueGenerator.getRandomValuesLocalizationMap(
				locales, _NAME_LENGTH);

		Map<Locale, String> descriptionMap =
			liferayGenValueGenerator.getRandomValuesLocalizationMap(
				locales, _DESCRIPTION_LENGTH);

		Document document = SAXReaderUtil.createDocument();

		Element rootElement = document.addElement("root");

		Locale siteDefault = LocaleUtil.getSiteDefault();

		rootElement.addAttribute("available-locales", siteDefault.toString());
		rootElement.addAttribute("default-locale", siteDefault.toString());

		_maxWcmImages = GetterUtil.getInteger(parameters.get("maxWcmImages"));

		boolean allowWcmImages = true;

		if (_maxWcmImages == 0) {
			allowWcmImages = false;
		}

		generateRandomStructureContent(
			liferayGenValueGenerator, parameters, rootElement, 1,
			allowWcmImages);

		ServiceContext serviceContext = new ServiceContext();

		long journalClassnameId = _classNameLocalService.getClassNameId(
			JournalArticle.class);

		DDMStructure journalStructure = _ddmStructureLocalService.addStructure(
			userId, groupId, parentStructureId, journalClassnameId, null,
			nameMap, descriptionMap, document.formattedString(), "xml",
			DDMStructureConstants.TYPE_DEFAULT, serviceContext);

		boolean addTemplate = Boolean.parseBoolean(
			MapUtil.getString(parameters, "addTemplate"));

		if (!addTemplate) {
			return;
		}

		addTemplate(liferayGenValueGenerator, parameters, journalStructure);
	}

	protected Element generateListOption(
		LiferayGenValueGenerator liferayGenValueGenerator) {

		Element optionElement = SAXReaderUtil.createElement("dynamic-element");

		String name = liferayGenValueGenerator.getLowerCaseText(
			liferayGenValueGenerator.getRandomIntegerFromRange(5, 12));

		name = name.replace(" ", "");

		optionElement.addAttribute("name", name);

		optionElement.addAttribute("type", "option");

		optionElement.addAttribute("value", name + "_value");

		Element metadataElement = SAXReaderUtil.createElement("meta-data");

		Locale siteDefault = LocaleUtil.getSiteDefault();

		metadataElement.addAttribute("locale", siteDefault.toString());

		Element entryElement = SAXReaderUtil.createElement("entry");

		entryElement.addAttribute("name", "label");

		entryElement.addCDATA(name + "_label");

		metadataElement.add(entryElement);

		optionElement.add(metadataElement);

		return optionElement;
	}

	protected Element generateListOptions(
		LiferayGenValueGenerator liferayGenValueGenerator, Element element) {

		int numOptions = liferayGenValueGenerator.getRandomIntegerFromRange(
			2, 10);

		for (int i = 0; i < numOptions; i++) {
			Element optionElement = generateListOption(
				liferayGenValueGenerator);

			element.add(optionElement);
		}

		return element;
	}

	protected void generateRandomStructureContent(
		LiferayGenValueGenerator liferayGenValueGenerator,
		Map<String, Object> parameters, Element rootElement, int depth,
		boolean allowWcmImages) {

		int maxFields = _MAX_FIELDS_PER_LEVEL;

		if (depth > 1) {
			maxFields = _MAX_FIELDS_PER_CHILD_LEVEL;
		}

		int numFields = liferayGenValueGenerator.getRandomIntegerFromRange(
			1, maxFields);

		int numWcmImages = 0;

		for (int i = 0; i < numFields; i++) {
			Element element = generateRandomStructureElement(
				liferayGenValueGenerator, parameters, allowWcmImages);

			rootElement.add(element);

			String type = element.attributeValue("type");

			if (type.equals("wcm-image")) {
				if (numWcmImages == _maxWcmImages) {
					allowWcmImages = false;
				}
				else {
					numWcmImages++;
				}
			}

			//List fields don't allow child fields

			if (!type.equals("radio") && !type.equals("select")) {
				boolean hasChildren = liferayGenValueGenerator.getBoolean();

				if (hasChildren && (depth <= _MAX_DEPTH)) {
					generateRandomStructureContent(
						liferayGenValueGenerator, parameters, element,
						depth + 1, allowWcmImages);
				}
			}

			String nameValue = element.attributeValue("name");

			Element metadataElement = SAXReaderUtil.createElement("meta-data");

			Locale siteDefault = LocaleUtil.getSiteDefault();

			metadataElement.addAttribute("locale", siteDefault.toString());

			Element entryLabelElement = SAXReaderUtil.createElement("entry");

			entryLabelElement.addAttribute("name", "label");

			entryLabelElement.addCDATA(nameValue + "_label");

			metadataElement.add(entryLabelElement);

			Element entryPredefinedValueElement = SAXReaderUtil.createElement(
				"entry");

			entryPredefinedValueElement.addAttribute("name", "predefinedValue");

			// TODO Generate proper predefined values

			entryPredefinedValueElement.addCDATA("");

			metadataElement.add(entryPredefinedValueElement);

			Element entryTipElement = SAXReaderUtil.createElement("entry");

			entryTipElement.addAttribute("name", "tip");

			entryTipElement.addCDATA(nameValue + "_tip");

			metadataElement.add(entryTipElement);

			element.add(metadataElement);
		}
	}

	protected Element generateRandomStructureElement(
		LiferayGenValueGenerator liferayGenValueGenerator,
		Map<String, Object> parameters, boolean allowWcmImages) {

		Element element = SAXReaderUtil.createElement("dynamic-element");

		String typeValue;

		if (!allowWcmImages) {
			typeValue = liferayGenValueGenerator.getRandomObjectFromList(
				_structureFieldDataTypesWithoutWCMImage);
		}
		else {
			typeValue = liferayGenValueGenerator.getRandomObjectFromList(
				_structureFieldTypes);
		}

		element.addAttribute("type", typeValue);

		if (!typeValue.equals("ddm-separator")) {
			String dataTypeValue = _structureFieldDataTypes.get(
				_structureFieldTypes.indexOf(typeValue));

			element.addAttribute("dataType", dataTypeValue);
		}

		String fieldNamespaceValue = typeValue.substring(0, 4);

		if (fieldNamespaceValue.endsWith("-")) {
			element.addAttribute(
				"fieldNamespace", fieldNamespaceValue.substring(0, 3));
		}

		int nameLength = liferayGenValueGenerator.getRandomIntegerFromRange(
			5, 12);

		String nameValue = liferayGenValueGenerator.getLowerCaseWord(
			nameLength);

		element.addAttribute("name", nameValue);

		int repeatableFieldRatio =
			_liferayGenParameterHandler.getParamAsIntegerPercentage(
				parameters, "repeatableFieldRatio");

		String repeatableValue = String.valueOf(
			liferayGenValueGenerator.getBoolean(repeatableFieldRatio));

		element.addAttribute("repeatable", repeatableValue);

		String readOnlyValue = String.valueOf(
			liferayGenValueGenerator.getBoolean());

		element.addAttribute("readOnly", readOnlyValue);

		String showLabelValue = String.valueOf(
			liferayGenValueGenerator.getBoolean());

		element.addAttribute("showLabel", showLabelValue);

		int localizedFieldRatio =
			_liferayGenParameterHandler.getParamAsIntegerPercentage(
				parameters, "localizedFieldRatio");

		String localizableValue = String.valueOf(
			liferayGenValueGenerator.getBoolean(localizedFieldRatio));

		element.addAttribute("localizable", localizableValue);

		if (typeValue.equals("checkbox") ||
			typeValue.equals("ddm-documentlibrary") ||
			typeValue.equals("wcm-image") || typeValue.equals("radio") ||
			typeValue.equals("select") || typeValue.equals("ddm-separator")) {

			element.addAttribute("width", "");
		}
		else {
			String widthValue = String.valueOf(
				liferayGenValueGenerator.getRandomObjectFromArray(_WIDTHS));

			element.addAttribute("width", widthValue);
		}

		String indexTypeValue;

		if (typeValue.contains("text")) {
			indexTypeValue = liferayGenValueGenerator.getRandomObjectFromList(
				_indexTypeFieldTypesWithText);
		}
		else {
			indexTypeValue = liferayGenValueGenerator.getRandomObjectFromList(
				_indexTypeFieldTypes);
		}

		element.addAttribute("indexType", indexTypeValue);

		if (typeValue.equals("radio") || typeValue.equals("select")) {
			element = generateListOptions(liferayGenValueGenerator, element);

			if (typeValue.equals("select")) {
				String multipleValue = String.valueOf(
					liferayGenValueGenerator.getBoolean());

				element.addAttribute("multiple", multipleValue);
			}
		}

		return element;
	}

	protected DDMStructure getRandomStructure(
		LiferayGenValueGenerator liferayGenValueGenerator, long groupId) {

		int count = _ddmStructureLocalService.getStructuresCount(groupId);

		if (count == 0) {
			return null;
		}

		int randomPos = liferayGenValueGenerator.getRandomIntegerFromRange(
			0, count - 1);

		List<DDMStructure> journalStructures =
			_ddmStructureLocalService.getStructures(
				groupId, randomPos, randomPos + 1);

		return journalStructures.get(0);
	}

	protected Element getStructureElements(DDMStructure ddmStructure)
		throws Exception {

		Element rootElement = null;

		appendParentStructureElements(
			ddmStructure.getParentStructureId(), rootElement);

		//TODO set as null by now
		//Document document = SAXReaderUtil.read(ddmStructure.getCompleteXsd());
		Document document = null;

		if (rootElement == null) {
			rootElement = document.getRootElement();
		}
		else {
			rootElement.add(document.getRootElement());
		}

		return rootElement;
	}

	private static final int _DEFAULT_CHILD_RATIO = 25;

	private static final int _DEFAULT_LOCALIZED_FIELD_RATIO = 60;

	private static final int _DEFAULT_MAX_WCM_IMAGES = 1;

	private static final int _DEFAULT_REPEATABLE_FIELD_RATIO = 20;

	private static final int _DESCRIPTION_LENGTH = 20;

	private static final int _MAX_DEPTH = 3;

	private static final int _MAX_FIELDS_PER_CHILD_LEVEL = 3;

	private static final int _MAX_FIELDS_PER_LEVEL = 8;

	private static final int _NAME_LENGTH = 10;

	private static final String[] _WIDTHS = {"small", "medium", "large"};

	private static final List<String> _indexTypeFieldTypes = new ArrayList<>(
		Arrays.asList("keyword", StringPool.BLANK));
	private static final List<String> _indexTypeFieldTypesWithText =
		new ArrayList<>(Arrays.asList("text", "keyword", StringPool.BLANK));
	private static final List<String> _structureFieldDataTypes =
		new ArrayList<>(
			Arrays.asList(
				"boolean", "date", "double", "document-library", "html",
				"image", "integer", "link-to-page", "number", "string",
				"string", StringPool.BLANK, "string", "string"));
	private static final List<String> _structureFieldDataTypesWithoutWCMImage =
		new ArrayList<>(
			Arrays.asList(
				"checkbox", "ddm-date", "ddm-decimal", "ddm-documentlibrary",
				"ddm-text-html", "ddm-integer", "ddm-link-to-page",
				"ddm-number", "radio", "select", "ddm-separator", "text",
				"textarea"));
	private static final List<String> _structureFieldTypes = new ArrayList<>(
		Arrays.asList(
			"checkbox", "ddm-date", "ddm-decimal", "ddm-documentlibrary",
			"ddm-text-html", "wcm-image", "ddm-integer", "ddm-link-to-page",
			"ddm-number", "radio", "select", "ddm-separator", "text",
			"textarea"));

	@Reference
	private ClassNameLocalService _classNameLocalService;

	@Reference
	private CompanyLocalService _companyLocalService;

	@Reference
	private DDMStructureLocalService _ddmStructureLocalService;

	@Reference
	private DDMTemplateLocalService _ddmTemplateLocalService;

	@Reference
	private ExpandoValueLocalService _expandoValueLocalService;

	@Reference
	private JournalArticleLocalService _journalArticleLocalService;

	@Reference
	private LiferayGenParameterHandler _liferayGenParameterHandler;

	@Reference
	private LiferayGenQueryHandler _liferayGenQueryHandler;

	private int _maxWcmImages;

	@Reference
	private Portal _portal;

	@Reference
	private PortletLocalService _portletLocalService;

}